version: 1
disable_existing_loggers: False

formatters:
  default:
    format: "%(asctime)s | %(levelname)s | %(name)s | %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

  color:
    (): colorlog.ColoredFormatter
    format: "%(log_color)s%(asctime)s | %(levelname)s | %(name)s | %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
    log_colors:
      DEBUG:    cyan
      INFO:     green
      WARNING:  yellow
      ERROR:    red
      CRITICAL: bold_red

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: color
    stream: ext://sys.stdout

  file:
    class: logging.FileHandler
    level: INFO
    formatter: default
    filename: logs/app.log
    encoding: utf8

loggers:
  my_app:
    level: DEBUG
    handlers: [console, file]
    propagate: no

root:
  level: INFO
  handlers: [console, file]